### PR TITLE
fix: bulk-download and bulk-create working

### LINKED ISSUE #31: bulk-create and bulk-download not working
Running `zendro bulk-download -n AlleleMatrix -f ./out` or `zendro bulk-create -f ~/Desktop/AlleleMatrix.csv -n AlleleMatrix`
>loaded model: alleleMatrix.js
WARNING: BulkAdd email service has not been properly configured {
  MAIL_ACCOUNT: '',
  MAIL_HOST: '',
  MAIL_PASSWORD: '',
  MAIL_SERVICE: ''
}
...
create associations among sql models
initialize storage handlers for adapters
TypeError: Cannot read properties of undefined (reading 'definition')
    at module.exports (/Users/f.sill/Desktop/laszlo/zendro/lib/bulk_download.js:37:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### PR DESCRIPTION
**Pull request by qwerdenkerXD**
This PR corrects some issues in code base that caused errors when trying to use `zendro bulk-download` or `zendro bulk-create` non-remotely (`-r` not set)

### CODE REVIEW

**Comment by qwerdenkerXD** [comment]
Line 36 should be generalized, is sql-only now

File: lib/bulk_download.js [hunk 1]
```diff
@@ -64,7 +63,7 @@ module.exports = async (options) => {
     header = header.slice(0, -1);
 
     const file_path = options.file_path
-      ? path.normalize(process.cwd() + "/" + options.file_path)
+      ? path.resolve(options.file_path)
```
Comment (wunderbarr) [inline lib/bulk_download.js:66]: have a look at Windows, whether `resolve` function works

File: lib/bulk_download.js [hunk 2]
```diff
@@ -64,7 +63,7 @@ module.exports = async (options) => {
...
       : path.normalize(
```
Comment (wunderbarr) [inline lib/bulk_download.js:67]: keep the consistency with resolve function

**Review by wunderbarr — CHANGES_REQUESTED** [review]

File: lib/bulk_download.js (hunk 1 above)
Comment (qwerdenkerXD) [reply lib/bulk_download.js:66]: works
